version: "3.9"
services:
  forecasts-service:
    build: .
    container_name: forecasts-service
    ports:
      - "${FORECASTS_SERVICE_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:${MONGO_PORT}/${MONGO_DB}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    environment:
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
